CREATE TABLE IF NOT EXISTS Aeroport (id INTEGER NOT NULL PRIMARY KEY ASC, oaci TEXT NOT NULL UNIQUE, aita TEXT NOT NULL, nom TEXT NOT NULL, latitude REAL NOT NULL, longitude REAL NOT NULL);


CREATE TABLE IF NOT EXISTS Avion(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  modele TEXT NOT NULL,
  numeroSerie TEXT NOT NULL,
  codeInterne TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS Mouvement (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  numeroVol TEXT NOT NULL,
  distance INTEGER NOT NULL,
  nbPassagers INTEGER NOT NULL,
  estIntracom INTEGER NOT NULL,
  dateHeureDepart TEXT NOT NULL,
  dateHeureArrivee TEXT NOT NULL,
  dureeVol INTEGER NOT NULL,
  AeroportDepart_oaci TEXT NOT NULL,
  AeroportArrivee_oaci TEXT NOT NULL,
  Avion_id INTEGER NOT NULL,
  FOREIGN KEY (AeroportDepart_oaci) REFERENCES Aeroport (oaci),
  FOREIGN KEY (AeroportArrivee_oaci) REFERENCES Aeroport (oaci),
  FOREIGN KEY (Avion_id) REFERENCES Avion (id)
);


CREATE TABLE IF NOT EXISTS Retard (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  commentaire TEXT NOT NULL,
  duree INTEGER NOT NULL,
  impliqueAeroport INTEGER NOT NULL,
  Mouvement_id INTEGER NOT NULL,
  TypeRetard_id INTEGER NOT NULL,
   FOREIGN KEY (TypeRetard_id) REFERENCES TypeRetard (id),
   FOREIGN KEY (Mouvement_id) REFERENCES Mouvement (id)
);

CREATE TABLE IF NOT EXISTS TypeRetard (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  codeSituation TEXT NOT NULL,
  nom TEXT NOT NULL
);
